library(mice)

cols <- c("numeric","numeric","numeric","numeric","numeric","factor","factor","factor","factor","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","factor","factor","factor","factor","factor","factor","factor")
data <- read.csv(url("https://raw.githubusercontent.com/jkartzman/AMS572-Project/main/chronic_kidney_disease.csv"),header = TRUE,colClasses = cols,na.strings = "?")

levels(data$X.class.) <- gsub("\t","",levels(data$X.class.))
levels(data$X.class.) <- gsub("notckd","0",levels(data$X.class.))
levels(data$X.class.) <- gsub("ckd","1",levels(data$X.class.))
levels(data$X.cad.) <- gsub("\t","",levels(data$X.cad.))
levels(data$X.cad.) <- gsub("no","0",levels(data$X.cad.))
levels(data$X.cad.) <- gsub("yes","1",levels(data$X.cad.))
levels(data$X.dm.) <- gsub(" ","",levels(data$X.dm.))
levels(data$X.dm.) <- gsub("\t","",levels(data$X.dm.))
levels(data$X.dm.) <- gsub("no","0",levels(data$X.dm.))
levels(data$X.dm.) <- gsub("yes","1",levels(data$X.dm.))
levels(data$X.appet.) <- gsub("good","1",levels(data$X.appet.))
levels(data$X.appet.) <- gsub("poor","0",levels(data$X.appet.))
levels(data$X.pe.) <- gsub("yes","1",levels(data$X.pe.))
levels(data$X.pe.) <- gsub("no","0",levels(data$X.pe.))
levels(data$X.ane.) <- gsub("yes","1",levels(data$X.ane.))
levels(data$X.ane.) <- gsub("no","0",levels(data$X.ane.))
levels(data$X.htn.) <- gsub("yes","1",levels(data$X.htn.))
levels(data$X.htn.) <- gsub("no","0",levels(data$X.htn.))
levels(data$X.rbc.) <- gsub("abnormal","0",levels(data$X.rbc.))
levels(data$X.rbc.) <- gsub("normal","1",levels(data$X.rbc.))
levels(data$X.pc.) <- gsub("abnormal","0",levels(data$X.pc.))
levels(data$X.pc.) <- gsub("normal","1",levels(data$X.pc.))
levels(data$X.pcc.) <- gsub("notpresent","0",levels(data$X.pcc.))
levels(data$X.pcc.) <- gsub("present","1",levels(data$X.pcc.))
levels(data$X.ba.) <- gsub("notpresent","0",levels(data$X.ba.))
levels(data$X.ba.) <- gsub("present","1",levels(data$X.ba.))

imp <- mice(data,m=5,maxit=5,seed=500)
data <- complete(imp)

data$X.class. <- as.numeric(as.character(data$X.class.))
data$X.cad. <- as.numeric(as.character(data$X.cad.))
data$X.dm. <- as.numeric(as.character(data$X.dm.))
data$X.appet. <- as.numeric(as.character(data$X.appet.))
data$X.pe. <- as.numeric(as.character(data$X.pe.))
data$X.ane. <- as.numeric(as.character(data$X.ane.))
data$X.htn. <- as.numeric(as.character(data$X.htn.))
data$X.rbc. <- as.numeric(as.character(data$X.rbc.))
data$X.pc. <- as.numeric(as.character(data$X.pc.))
data$X.pcc. <- as.numeric(as.character(data$X.pcc.))
data$X.ba. <- as.numeric(as.character(data$X.ba.))

train_data <- data[21:380,]
test_data <- data[c(1:20,381:400),]
model <- glm(X.class.~.,data=train_data,family="binomial")
probs <- predict(model,newdata=test_data,type = "response")
preds <- ifelse(probs > 0.5,1,0)
